title: Laksvision
description: Computer Vision • Deep Learning • System Design
baseurl: ""
url: "https://lakshmikanthgr.github.io"
collections:
  notes:
    output: true
    permalink: /notes/:path/
markdown: kramdown